# Generated by Django 3.1.6 on 2021-05-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=130, unique=True, verbose_name='Slug'),
        ),
    ]
